### ISSUE TITLE
Comment gets darker when inside region

### ISSUE THREAD

**Issue by felipebalbi** [aaronjensen/night-owl-emacs#2]
Have you than when you put a region which contains comments, the contrast between text and region is too little?

![image](https://user-images.githubusercontent.com/45936891/62696833-f0307b00-b9e1-11e9-8058-562ed0ef8310.png)

I've been trying to figure out which font face emacs is using to do that but I couldn't find. If you know which one it is, then I can produce a pull request to fix that, no problem. Cheers

**Comment by aaronjensen** [comment]
This should be fixed now, give it a shot.

**Comment by felipebalbi** [comment]
Awesome, thanks :-)
