### ISSUE TITLE
Question: is there a setting to get the colors to render properly in the emacs app for MacOS?

### ISSUE THREAD

**Issue by pbeshai** [aaronjensen/night-owl-emacs#4]
Hi there, I'm just starting to explore using Spacemacs and running into issues getting the coloring to work properly using the [MacOS emacs app](https://emacsformacosx.com). Do you have any ideas on how I might get it set up properly?

(left is emacs, right is VS Code)
![image](https://user-images.githubusercontent.com/793847/63564497-426db200-c533-11e9-8e08-40c5a7c99060.png)

(using javascript as the language here with the `javascript` layer on)

Any ideas would be very helpful (sorry if this is an inappropriate place to ask!)

**Comment by aaronjensen** [comment]
Hi there, are you using this theme? The background color looks wrong. The other things look fairly close, however. 

As far as it matching exactly, it's unlikely that this theme will ever match things exactly as vs code and the various emacs modes don't always allow for differentiating syntax in the same way. It's also possible that this has gotten out of sync with the vs code version (the numbers look particularly suspect).

**Comment by pbeshai** [comment]
Thanks for your help! After some more digging this morning I discovered it was because there was something at the very bottom of my .spacemacs file:

```elisp
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
'(default ((t (:foreground "#D8DEE9" :background "#1B2B34"))))
 )
```

Not sure how that got there, but commenting out the `'(default ...)` line got the background working properly.
