### ISSUE TITLE
Them has issue in terminal environment

### ISSUE THREAD

**Issue by mortymacs** [aaronjensen/night-owl-emacs#6]
I want to use it in the terminal environment, but it has some issues (e.g. background color):
![Screenshot from 2020-01-13 22-54-43](https://user-images.githubusercontent.com/1261448/72295417-ceee4d80-3657-11ea-997e-c1a400acf050.png)

**Comment by aaronjensen** [comment]
Hi @mortezaipo I don't actually have any intent of supporting 256 color environments. If you're using a terminal capable of displaying 24 bit color, it's possible for Emacs 26+ to display 24 bit color in a terminal. In that case, it looks quite good. I don't have any guides on hand, but if you search around you can find how to configure your terminal and emacs to support 24bit. If you find a good guide, you could reply here and I can add it to the readme.

Thanks!

**Comment by coldfish** [comment]
I followed up this tutorial and it worked without a problem:

http://www.skybert.net/emacs/colourful-tty-emacs/
